"""empty message

Revision ID: d034157136b9
Revises: 1da9b8577dab
Create Date: 2022-05-20 01:45:30.654285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd034157136b9'
down_revision = '1da9b8577dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('book_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'book_id')
    # ### end Alembic commands ###
